// Mocks generated by Mockito 5.4.6 from annotations
// in country_info/test/features/country/data/datasource/country_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:country_info/core/data/network/api/graphql_api_client.dart'
    as _i3;
import 'package:country_info/core/data/network/api/graphql_query_result.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGraphQLQueryResult_0 extends _i1.SmartFake
    implements _i2.GraphQLQueryResult {
  _FakeGraphQLQueryResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GraphQLApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphQLApiClient extends _i1.Mock implements _i3.GraphQLApiClient {
  MockGraphQLApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GraphQLQueryResult> query({
    required String? query,
    Map<String, dynamic>? variables,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#query, [], {
              #query: query,
              #variables: variables,
            }),
            returnValue: _i4.Future<_i2.GraphQLQueryResult>.value(
              _FakeGraphQLQueryResult_0(
                this,
                Invocation.method(#query, [], {
                  #query: query,
                  #variables: variables,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.GraphQLQueryResult>);
}
