// Mocks generated by Mockito 5.4.6 from annotations
// in country_info/test/features/country/data/repository/country_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:country_info/features/country/data/datasource/country_datasource.dart'
    as _i3;
import 'package:country_info/features/country/data/models/country_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCountryModel_0 extends _i1.SmartFake implements _i2.CountryModel {
  _FakeCountryModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CountryDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountryDataSource extends _i1.Mock implements _i3.CountryDataSource {
  MockCountryDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.CountryModel>> getCountries() =>
      (super.noSuchMethod(
            Invocation.method(#getCountries, []),
            returnValue: _i4.Future<List<_i2.CountryModel>>.value(
              <_i2.CountryModel>[],
            ),
          )
          as _i4.Future<List<_i2.CountryModel>>);

  @override
  _i4.Future<_i2.CountryModel> getCountryDetails(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getCountryDetails, [code]),
            returnValue: _i4.Future<_i2.CountryModel>.value(
              _FakeCountryModel_0(
                this,
                Invocation.method(#getCountryDetails, [code]),
              ),
            ),
          )
          as _i4.Future<_i2.CountryModel>);
}
